Update to `mypy==1.16.1`
Mypy 1.16.1 detects a type error, undetected in previous mypy versions,
in the `on_error` argument to `AuthenticationMiddleware.__init__()` in
`inboard.app.main_starlette`.

```text
inboard/app/main_starlette.py:56:
error: Argument "on_error" to "Middleware" has incompatible type
"Callable[[Request, Exception], JSONResponse]";
expected "Callable[[HTTPConnection, AuthenticationError], Response] | None"  [arg-type]
```

The `on_auth_error` callable had the first argument incorrectly type
annotated as `starlette.requests.Request` when it should have been
`starlette.requests.HTTPConnection`. The second argument is annotated in
Starlette as `starlette.exceptions.AuthenticationError`, which inherits
from `Exception` and is merely a `pass`.