Update Vercel configuration for uv
Vercel apparently switched to a uv-managed Python installation on their
build runners without telling anyone. Back in October, Vercel posted a
changelog entry saying that uv was "available" but nothing saying that
the Python installation itself was going to be managed with uv also.

The current commands have started raising externally-managed-environment
errors since the last Vercel docs deployments a few weeks ago.

```
Build machine configuration: 2 cores, 8 GB
Cloning github.com/br3ndonland/inboard (Branch: develop, Commit: a9cd45f)
Previous build caches not available.
Cloning completed: 569.000ms
Running "vercel build"
Vercel CLI 50.4.10
Running "install" command: `python3 -m pip install --user pipx && export PATH="$HOME/.local/bin:$PATH" && pipx install --global --include-deps 'mkdocs-material>=9,<10'`...
error: externally-managed-environment
× This environment is externally managed
╰─> This Python installation is managed by uv and should not be modified.
note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
Error: Command "python3 -m pip install --user pipx && export PATH="$HOME/.local/bin:$PATH" && pipx install --global --include-deps 'mkdocs-material>=9,<10'" exited with 1
```

On top of that, Vercel doesn't add the uv tool directory to `$PATH`.
Users must manually modify `$PATH` to prevent errors like the following.

```
Installed 1 executable: hatch
warning: `/vercel/.local/bin` is not on your PATH. To use installed tools, add the directory to your PATH.
sh: line 1: hatch: command not found
Error: Command "hatch run docs:mkdocs build --site-dir public" exited with 127
```

This commit will update `vercel.json` to install Hatch with uv. Hatch
will then be used to install dependencies for building the docs.

https://peps.python.org/pep-0668/
https://packaging.python.org/en/latest/specifications/externally-managed-environments/
https://vercel.com/changelog/python-package-manager-uv-is-now-available-for-builds-with-zero