Update to `mypy==1.7.0`
The new `type: ignore` is needed to resolve the following error:

```text
inboard/logging_conf.py:48: error:
Argument 1 to "dictConfig" has incompatible type "DictConfig";
expected "_DictConfigArgs | dict[str, Any]"  [arg-type]
```