Correct Mypy assignment error in gunicorn_conf.py
Mypy error: https://mypy.readthedocs.io/en/latest/error_code_list.html

```text
Incompatible types in assignment (expression has type "None", variable
has type "Dict[str, Any]") [assignment] mypy(error)
```

Source of error: `logconfig_dict` was potentially assigned to `None`.

Other changes:

- Inboard import will also be corrected to package module path
- Remove `# type: ignore` comment on inboard as it is no longer needed