Update to FastAPI 0.100
This commit will update/upgrade to
[FastAPI 0.100](https://fastapi.tiangolo.com/release-notes/).

FastAPI 0.100 includes support for
[Pydantic 2](https://docs.pydantic.dev/2.0/migration/)
and installs Pydantic 2 by default, which can be a **BREAKING CHANGE**
depending on each project's usage of Pydantic.

How to deal with this breaking change:

- First, update requirements files with `"pydantic==1.*"` to avoid
  automatically updating to Pydantic 2.
- Next, remove `"pydantic==1.*"` from requirements files,
  install Pydantic 2, and follow the
  [Pydantic 2 migration guide](https://docs.pydantic.dev/2.0/migration/).

This commit will also make a small update to the default FastAPI app to
fix a Mypy error:

```text
inboard/app/main_fastapi.py:60:
error: Missing named argument "message" for "GetStatus"  [call-arg]
```